services:
  - type: web
    name: laravel-app
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:TdaiTkQ3uVtPziz7VE/N5W0OcorMx1r2WOGQkHItyAU=
      - key: APP_URL
        value: https://task-list-cdu9.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 0.0.0.0
      - key: DB_PORT
        value: $PORT
      - key: DB_DATABASE
        value: task_list_pgs
      - key: DB_USERNAME
        value: task_list_pgs_userl
      - key: DB_PASSWORD
        value: xORvEDFEm5MxZXXZwMPPnO8ShBuCxweC

